changelog:
  categories:
    - title: 🆕 New Features
      labels:
        - "new-feature"
    - title: ⚙️ New Settings
      labels:
        - "new-setting"
    - title: 🔧 General Improvements
      labels:
        - "general-improvement"
    - title: 🐛 Bug Fixes
      labels:
        - "bug-fix"
    - title: 🧹 Code Cleanup
      labels:
        - "code-cleanup"
    - title: 💻 Dev Improvements
      labels:
        - "dev-improvement"
    - title: 📝 Documentation
      labels:
        - "documentation"
    - title: ⭐ Additional Updates
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - ignore-changelog
