# Builds the production version of the app
name: build-prod

on:
  workflow_call:

jobs:
  prod:
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Build app for production
        run: npm run build-prod
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: Jellyfin-Roku-v${{ env.newManVersion }}-${{ github.sha }}
          path: ${{ github.workspace }}/build/staging
          if-no-files-found: error
