name: lint-json

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone github repo
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install npm dependencies
        run: npm ci
      - name: Install roku package dependencies
        run: npx ropm install
      - name: Validate JSON syntax
        run: npm run lint-json