name: Automation 🤖

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - unstable
  pull_request_target:

jobs:
  project:
    name: Project board 📊
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43 # v0.8.3
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true
        with:
          project: Ongoing development
          column: In progress
          repo-token: ${{ secrets.JF_BOT_TOKEN }}
  label:
    name: Labeling 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Check all PRs for merge conflicts ⛔
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflict"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
