name: "Close stale Pull Requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    if: github.repository == 'jellyfin/jellyfin-roku'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-label: stale
          stale-pr-message: "This pull request has been inactive for 30 days and will be automatically closed in 15 days if there is no further activity."
          close-pr-message: "This pull request has been closed because it has been inactive for 45 days. You may submit a new pull request if desired."
          days-before-pr-stale: 30
          days-before-pr-close: 15
          exempt-draft-pr: true
          repo-token: ${{ secrets.JF_BOT_TOKEN }}
