name: "Close stale Pull Requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 # tag=v6
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-message: "This pull request has been inactive for 21 days and will be automatically closed in 7 days if there is no further activity."
          close-pr-message: "This pull request has been closed because it has been inactive for 28 days. You may submit a new pull request if desired."
          days-before-pr-stale: 21
          days-before-pr-close: 7
          repo-token: ${{ secrets.GITHUB_TOKEN }}
