name: "Close stale Pull Requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b # v7
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-message: "This pull request has been inactive for 21 days and will be automatically closed in 7 days if there is no further activity."
          close-pr-message: "This pull request has been closed because it has been inactive for 28 days. You may submit a new pull request if desired."
          days-before-pr-stale: 21
          days-before-pr-close: 7
          exempt-draft-pr: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
