name: build
on:
  pull_request:
  push:
    paths-ignore:
      - 'locale/**'
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: "14.12.0"
      - run: npm ci
      - run: npx ropm install
      - run: make dev
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
        with:
          name: Jellyfin-Roku-dev-${{ github.sha }}
          path: ${{ github.workspace }}/out/staging
          if-no-files-found: error
