name: build

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches:
      - unstable

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npx ropm install
      - run: make dev
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: Jellyfin-Roku-dev-${{ github.sha }}
          path: ${{ github.workspace }}/out/staging
          if-no-files-found: error