name: build-dev

on:
  pull_request:
  push:

jobs:
  dev:
    # prevent job from running twice when a PR pushes a new commit
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Build app
        run: npm run build
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: Jellyfin-Roku-dev-${{ github.sha }}
          path: ${{ github.workspace }}/build/staging
          if-no-files-found: error
