name: dependencies

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  validate:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    uses: ./.github/workflows/_validate-dependencies.yml
