name: 'Notify of Merge Conflicts'

on:
  push:
    branches:
      - unstable
  pull_request_target:
    types:
      - synchronize

jobs:
  run:
    name: 'Merge conflict labeling'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-roku' }}
    steps:
      - uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}