name: roku-analysis

on:
  pull_request:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Build dev app
        if: env.BRANCH_NAME != 'master'
        run: npm run build
      - name: Build app for production
        if: env.BRANCH_NAME == 'master'
        run: npm run build-prod
      - name: Use Java 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Download the Static Channel Analysis CLI
        run: |
          curl -sSL "https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip" -o sca-cmd.zip
          unzip sca-cmd.zip
      - name: Run Roku Static Analysis
        run: ./sca-cmd/bin/sca-cmd ${{ github.workspace }}/build/staging --exit error
