name: validate
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14.12.0"
      - run: npm ci
      - run: npx ropm install
      - run: npm run validate
      - run: npm run check-formatting
