name: validate-xml
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone github repo
        uses: actions/checkout@master
      - name: Install xmllint and xmlstarlet using apt (from cache)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils xmlstarlet
      - name: Validate XML syntax
        run: xmllint --noout ./locale/*/*.ts
      - name: Check XML for duplicate entries
        run: xmlstarlet sel -t -m '/TS/context/message/source' -o 'Duplicate entry found in:' -f -o ' ' -c '.' -nl ./locale/*/*.ts | sort | uniq -d